### ISSUE TITLE
support for Bull 4 

### ISSUE THREAD

**Issue by arkhamRejek** [vcapretz/bull-board#38]
are you guys planning on supporting BullMQ 4 ?

**Comment by vcapretz** [comment]
hey @arkhamRejek, thanks for bringing this up! 

for sure we can look into supporting BullMQ 4. We would need to come up with the best way to do it, either by just bumping bull-board with a major changing or some other API's, if you have any suggestions please feel free to open a PR 😄

**Comment by arkhamRejek** [comment]
i'll take a look at their api later on today, someone mentioned that the api was pretty similar to Version 3 so i'll look at this source and get back to you. Great work btw, very beautiful UI.

**Comment by alubbe** [comment]
We're also wanting to upgrade to bull 4 (see https://github.com/bee-queue/arena/issues/199), so if it's helpful we wanted to share that I reached out to Manuel from taskforce.sh and he told me that
- it should not be very difficult to add support (for bull 4) since it provides a backwards compatibility class that implement most of the old API
- no more breaking changes (to bull 4) are planned, only fixes for now

**Comment by arkhamRejek** [comment]
@alubbe i played around with it a few just been too busy to sit, i hacked together some stuff but hopefully over the christmas break i'll look and see if i can create a pull if someone doesn't beat me to it

**Comment by arkhamRejek** [comment]
@alubbe i played around with it a few just been too busy to sit, i hacked together some stuff but hopefully over the christmas break i'll look and see if i can create a pull if someone doesn't beat me to it. kind of hard to get a good read on it as well since the tests are kind of vague as well

**Comment by arkhamRejek** [comment]
also the only exception thus far that i'm getting is at gets stats 
which is an easy fix since info seems to have been deprecated.
```javascript
 queue.client.info()
```

@vcapretz going to need your help on that
after
```javascript 
    const client = await queue.client
```
