### ISSUE TITLE
Module documentation

### ISSUE THREAD

**Issue by mtavano** [vcapretz/bull-board#94]
Hey folks! first of all, I hope to all of you having a good and stay healthy time on this covid-19 hard times.

I don't know if this could be considered as an issue but I was reading the source code and found that there a few extra definitions that are missing on the README 

```javascript
router.put('/queues/:queueName/retry', wrapAsync(retryAll))
router.put('/queues/:queueName/:id/retry', wrapAsync(retryJob))
router.put('/queues/:queueName/:id/promote', wrapAsync(promoteJob))
router.put('/queues/:queueName/clean/:queueStatus', wrapAsync(cleanAll))
```
so want to ask if there is an official doc or something to understand what are those routes and which role are playing on the board module

besides that, I didn't found in README regarding my server being hit at this route `GET /queues/queues/?` and the server is replying with 304 :thinking:

if anyone can help me will be very appreciated

**Comment by vcapretz** [comment]
hey, @mtavano 👋 
I hope you're good and healthy as well! 

these routes you pointed are used internally for bull-board, since we provide a UI for you to visualize and manage your Bull jobs we use these routes when you press the "retry" button on a job for instance.

It's nothing fancy behind these routes TBH, it's something you could accomplish in your application using bull's API directly 👍
